import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("http://practice.automationtesting.in/")

driver.execute_script("window.scrollBy(0, 600);")
selenium_ruby_btn = driver.find_element_by_css_selector("a[href='http://practice.automationtesting.in/product/selenium-ruby/']>h3").click()
time.sleep(1)
reviews_btn = driver.find_element_by_css_selector("a[href='#tab-reviews']").click()
time.sleep(1)
rating_btn = driver.find_element_by_css_selector("a.star-5").click()
time.sleep(1)
my_review = driver.find_element_by_css_selector("textarea#comment")
my_review.send_keys("Nice book!")
name = driver.find_element_by_css_selector("input#author")
name.send_keys("Andrew")
email = driver.find_element_by_css_selector("input#email")
email.send_keys("Andrew@andreeff.com")
submit = driver.find_element_by_css_selector("input#submit").click()
time.sleep(3)
driver.quit()